---
title: "COVID19 by province in Canada"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r}

Sys.time()

```

```{r}

print('WARNING: Potential errors in the code used to process the raw data prior to plotting may lead to display of inaccurate data. Accuracy of the plotted data has not been varified.')

print('WARNING: The most recent data from this source is sometimes not accurate')

```


```{r setup, include = F}
#Get libraries

library(data.table)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(flexdashboard)
#library(shinydashboard)

```

```{r, include = F}

#Set the threshold number from which to start plotting
case_thresh <- 1 
death_thresh <- 1

```

```{r, include = F}
#Get and process data

covid_raw <- fread('https://health-infobase.canada.ca/src/data/covidLive/covid19.csv')

time <- as.character(Sys.time())
time2 <- gsub(time, pattern = " ", replacement =  "_")
time3 <- gsub(time2, pattern = ":", replacement = "-")

filename_cvd <- paste('covid_data_canada', time3, ".csv", sep = "-")

write.csv(covid_raw, file= paste0('data/', filename_cvd), row.names = F)

#head(covid_raw)
#str(covid_raw)

#Get rows with NAs of confirmed cases

na_casescnf <- covid_raw %>%
  dplyr::filter(., is.na(numconf)) %>%
  dplyr::filter(., !(prname == "Repatriated travellers")) %>%
  dplyr::select(., prname, date, numconf)

na_death <- covid_raw %>%
  dplyr::filter(., is.na(numdeaths)) %>%
  dplyr::filter(., !(prname == "Repatriated travellers")) %>%
  dplyr::select(., prname, date, numdeaths)

west_can <- c("British Columbia",
              "Alberta",
              "Manitoba", 
              "Saskatchewan")

east_can <- c("Quebec",
              "Ontario")

mar_can <- c("New Brunswick",
             "Nova Scotia",
             "Prince Edward Island",
             "Newfoundland and Labrador")

nor_can <- c("Yukon", 
             "Northwest Territories",
             "Nunavut")

covid_1 <- covid_raw %>%
  dplyr::mutate(., numconf = as.numeric(numconf)) %>%
  dplyr::mutate(., numdeaths = as.numeric(numdeaths)) %>%
  dplyr::mutate(., Date = as.POSIXct(date, format = "%d-%m-%Y")) %>%
  dplyr::mutate(., day = format(Date, format = '%d')) %>%
  dplyr::mutate(., month = format(Date, format = '%m')) %>%
  dplyr::mutate(., year = format(Date, format = '%Y')) %>%
  dplyr::mutate(., doy = yday(Date)) %>%
  dplyr::mutate(., seconds = as.numeric(Date)) %>%
  dplyr::filter(., !(prname %in% c("Repatriated Travellers", "Repatriated travellers"))) %>%
  dplyr::mutate(., region = ifelse(prname %in% west_can, 'West', 'no_region')) %>%
  dplyr::mutate(., region = ifelse(prname %in% east_can, 'East', region)) %>%
  dplyr::mutate(., region = ifelse(prname %in% mar_can, 'Maritimes', region)) %>%
  dplyr::mutate(., region = ifelse(prname %in% nor_can, 'North', region))

canada_data <- covid_1 %>%
  dplyr::filter(., prname == "Canada")

```

Total cases and deaths (Canada)
===

###Cases
```{r}
conf_total <- max(canada_data$numconf)
valueBox(value = conf_total, icon = "fa-thermometer-three-quarters", color = "danger")
```


###Deaths
```{r}
deaths_total <- max(canada_data$numdeaths)
valueBox(value = deaths_total, icon = "fa-feather-alt", color = "primary")
```

Timeline
===

```{r, include = F}

#Get data for Timeline plots
covid_case <- covid_1 %>%
  dplyr::filter(., numconf >0)

latest_time <- max(covid_1$seconds)

latest_date_plus1day <- max(covid_1$Date) + (60*60*24*3)

earliest_date_case <- min(covid_case$Date)

covid_case_latest <- covid_case %>%
  dplyr::filter(., seconds == latest_time)

#Get gg object - cases
p_cases <- ggplot() +
  geom_point(data = covid_case, aes(x = Date, y = numconf, group = prname), alpha = 0.2) +
  geom_line(data = covid_case, aes(x = Date, y = numconf, colour = prname)) +
  geom_label_repel(data = covid_case_latest, aes(x = Date, y = numconf, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log2', limits = c(1, max(covid_case$numconf))) +
  scale_x_datetime(limits = c(earliest_date_case, latest_date_plus1day)) +
  ylab('Cumulative number of cases')

#Get gg object - deaths

##Get similar plot for deaths

covid_death <- covid_1 %>%
  dplyr::filter(numdeaths > 0)

covid_death_latest <- covid_death %>%
  dplyr::filter(., seconds == latest_time)

latest_date_plus1day_death <- max(covid_death$Date) + (60*60*24*3)

earliest_date_death <- min(covid_death$Date)

p_deaths <- ggplot() +
  geom_point(data = covid_death, aes(x = Date, y = numdeaths, group = prname), alpha = 0.2) +
  geom_line(data = covid_death, aes(x = Date, y = numdeaths, colour = prname)) +
  geom_label_repel(data = covid_death_latest, aes(x = Date, y = numdeaths, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log2', limits = c(1, max(covid_death$numdeaths))) +
  scale_x_datetime(limits = c(earliest_date_death, latest_date_plus1day_death)) +
  ylab('Cumulative number of deaths')

```

Column {.tabset .tabset-fade}
-------------------------------------

### Confirmed cases - timeline

```{r, 'fig.width' = 10}

print(p_cases)

```

### Deaths - timeline

```{r, 'fig.width' = 10}

print(p_deaths)
```

Trajectory 
===

```{r, include = F}
#Get data for trajectory plots

covid_cases_cnf <- covid_1 %>%
  dplyr::filter(., numconf >= case_thresh) %>%
  dplyr::group_by(., region, prname) %>%
  dplyr::summarise(., doy0_case = min(doy)) %>%
  dplyr::full_join(., covid_1) %>%
  dplyr::filter(., !(is.na(numconf))) %>%
  dplyr::mutate(., new_day_case = doy-doy0_case) %>%
  dplyr::mutate(., numconf = numconf - case_thresh) %>%
  dplyr::ungroup(.) %>%
  dplyr::mutate(., region = factor(region, levels = c("West", "East", "Maritimes", "North")))

covid_death <- covid_1 %>%
  dplyr::filter(., numdeaths > 0) %>%
  dplyr::group_by(., region, prname) %>%
  dplyr::summarise(., doy0_death = min(doy)) %>%
  dplyr::full_join(., covid_cases_cnf) %>%
  dplyr::filter(., !(is.na(numdeaths))) %>%
  dplyr::mutate(., new_day_death = doy-doy0_death) %>%
  dplyr::mutate(., numdeaths = numdeaths - death_thresh) %>%
  dplyr::ungroup(.) %>%
  dplyr::mutate(., region = factor(region, levels = c("West", "East", "Maritimes", "North")))

```

```{r, include = F}

#Get trajectory plots
case_label <- covid_cases_cnf %>%
  dplyr::group_by(., region, prname) %>%
  dplyr::summarise(., label_day = max(new_day_case),
                   label_case = max(numconf)) %>%
  dplyr::mutate(., label_day = ifelse(is.na(label_day), -100, label_day))

days_case <- seq(from = 0, to = max(case_label$label_day), by = 0.1)
db1 <- 2^(days_case)
db2<- 2^((days_case)/2)
db3 <- 2^((days_case)/4)

db_case <- data.frame(days_case, db1, db2, db3)

p_new_cases <- ggplot() +
  geom_line(data = covid_cases_cnf, aes(x = new_day_case, numconf, colour = prname)) +
  geom_point(data = covid_cases_cnf, aes(x = new_day_case, y = numconf, group = prname), alpha = 0.2) +
  geom_line(data = covid_cases_cnf, aes(x = new_day_case, y = numconf, colour = prname)) +
  geom_label_repel(data = case_label, aes(x = label_day, y = label_case, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log2', limits = c(1, max(covid_cases_cnf$numconf))) +
  scale_x_continuous(limits = c(-1, max(covid_cases_cnf$new_day_case))) +
  xlab(paste('Day since', case_thresh, 'cases', sep = " ")) +
  ylab('Cumulative number of cases') +
  geom_line(data = db_case, aes(x = days_case + 1, y = db1), size = 2, alpha = 0.2) +
  geom_line(data = db_case, aes(x = days_case + 1, y = db2), size = 2, alpha = 0.2) +
  geom_line(data = db_case, aes(x = days_case + 1, y = db3), size = 2, alpha = 0.2)

p_new_cases_r <- p_new_cases +
  facet_wrap(~region)

death_label <- covid_death %>%
  dplyr::group_by(., region, prname) %>%
  dplyr::summarise(., label_day = max(new_day_death),
                   label_death = max(numdeaths)) %>%
  dplyr::mutate(., label_day = ifelse(is.na(label_day), -100, label_day))

days_death <- seq(from = 0, to = max(death_label$label_day), by = 0.1)
db1 <- 2^(days_death)
db2<- 2^(days_death/2)
db3 <- 2^(days_death/4)

db_death <- data.frame(days_death, db1, db2, db3)

p_new_deaths <- ggplot() +
  geom_line(data = covid_death, aes(x = new_day_death, numdeaths, colour = prname)) +
  geom_point(data = covid_death, aes(x = new_day_death, y = numdeaths, group = prname), alpha = 0.2) +
  geom_line(data = covid_death, aes(x = new_day_death, y = numdeaths, colour = prname)) +
  geom_label_repel(data = death_label, aes(x = label_day, y = label_death, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log2', limits = c(1, max(covid_death$numdeaths))) +
  scale_x_continuous(limits = c(-1, max(death_label$label_day) + 2)) +
  xlab('Day since 1st death') +
  ylab('Cumulative number of deaths') +
  geom_line(data = db_death, aes(x = days_death, y = db1), size = 2, alpha = 0.2) +
  geom_line(data = db_death, aes(x = days_death, y = db2), size = 2, alpha = 0.2) +
  geom_line(data = db_death, aes(x = days_death, y = db3), size = 2, alpha = 0.2)

p_new_deaths_r <- p_new_deaths +
  facet_wrap(~region)

```

```{r}

##Get new cases

pr_names <- unique(covid_cases_cnf$prname) 
daily_cases_ls <- list()
daily_deaths_ls <- list()

for(i in pr_names) {
  
  cases_daily_tmp <- subset(covid_cases_cnf, prname == i)
  deaths_daily_tmp <- subset(covid_death, prname == i)
  
  diff_cases <- diff(cases_daily_tmp$numconf)
  diff_deaths <- diff(deaths_daily_tmp$numdeaths)
  diff_tests <- diff(cases_daily_tmp$numtested)
  
  daily_cases_ls[[i]] <- data.frame(cases_daily_tmp, new_cases = c(0, diff_cases), new_tests = c(0, diff_tests))
  daily_deaths_ls[[i]] <- data.frame(deaths_daily_tmp, new_deaths = c(0, diff_deaths))
  
}

daily_cases_df <- do.call(rbind, daily_cases_ls)
daily_deaths_df <- do.call(rbind, daily_deaths_ls)

daily_case_label <- daily_cases_df %>%
  dplyr::group_by(., prname) %>%
  dplyr::summarise(., label_day = max(new_day_case),
                   label_case = tail(new_cases, n = 1),
                   label_test = tail(new_tests, n = 1), 
                   label_Date = tail(Date, n = 1)) %>%
  dplyr::mutate(., label_day = ifelse(is.na(label_day), -100, label_day)) %>%
  dplyr::mutate(., label_test = ifelse(label_test == 0, 1, label_test))

daily_death_label <- daily_deaths_df %>%
  dplyr::group_by(., prname) %>%
  dplyr::summarise(., label_day = max(new_day_death),
                   label_death = tail(new_deaths, n = 1)) %>%
  dplyr::mutate(., label_day = ifelse(is.na(label_day), -100, label_day))
  

##Plot daily cases

p_daily_cases <- ggplot() +
  geom_line(data = daily_cases_df, aes(x = new_day_case, new_cases, colour = prname)) +
  geom_point(data = daily_cases_df, aes(x = new_day_case, y = new_cases, group = prname), alpha = 0.2) +
  geom_line(data = daily_cases_df, aes(x = new_day_case, y = new_cases, colour = prname)) +
  geom_label_repel(data = daily_case_label, aes(x = label_day, y = label_case, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log2', limits = c(1, max(daily_cases_df$new_cases))) +
  scale_x_continuous(limits = c(-1, max(daily_cases_df$new_day_case))) +
  xlab(paste('Day since', case_thresh, 'cases', sep = " ")) +
  ylab('New cases')

p_daily_deaths <- ggplot() +
  geom_line(data = daily_deaths_df, aes(x = new_day_death, new_deaths, colour = prname)) +
  geom_point(data = daily_deaths_df, aes(x = new_day_death, y = new_deaths, group = prname), alpha = 0.2) +
  geom_line(data = daily_deaths_df, aes(x = new_day_death, y = new_deaths, colour = prname)) +
  geom_label_repel(data = daily_death_label, aes(x = label_day, y = label_death, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log2', limits = c(1, max(daily_deaths_df$new_deaths))) +
  scale_x_continuous(limits = c(-1, max(daily_deaths_df$new_day_death))) +
  xlab(paste('Day since', case_thresh, 'deaths', sep = " ")) +
  ylab('New deaths')


```
Column {.tabset .tabset-fade}
-------------------------------------

### Cumulative confirmed cases - trajectory

```{r, 'fig.width' = 10, 'fig.cap' = 'The grey lines indicate doubling times at 1, 2, and 4 days'}

print(p_new_cases)

```

### New confirmed cases - trajectory

```{r, 'fig.width' = 10}

print(p_daily_cases)

```

### Cumulative deaths - trajectory

```{r, 'fig.width' = 10, 'fig.cap' = 'The grey lines indicate doubling times at 1, 2, and 4 days'}

print(p_new_deaths)

```

### New deaths - trajectory

```{r, 'fig.width' = 10}

print(p_daily_deaths)

```

<!-- Testing -->
<!-- === -->

```{r, include = F}

covid_test <- covid_1 %>%
  dplyr::filter(!(is.na(numtested)))

covid_test_latest <- covid_case_latest

earliest_test_case <- min(covid_test$Date)

#Get gg object - tests
p_tests <- ggplot() +
  geom_point(data = covid_test, aes(x = Date, y = numtested, group = prname), alpha = 0.2) +
  geom_line(data = covid_test, aes(x = Date, y = numtested, colour = prname)) +
  geom_label_repel(data = covid_test_latest, aes(x = Date, y = numtested, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log10', limits = c(1, max(covid_case$numtested))) +
  scale_x_datetime(limits = c(earliest_test_case, latest_date_plus1day)) +
  ylab('Cumulative number of tests')

##Tests - daily

p_test_daily <- ggplot() +
  geom_point(data = daily_cases_df, aes(x = Date, y = new_tests, group = prname), alpha = 0.2) +
  geom_line(data = daily_cases_df, aes(x = Date, y = new_tests, colour = prname)) +
  geom_label_repel(data = data.frame(daily_case_label), aes(x = label_Date, y = label_test, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log10', limits = c(1, max(covid_case$numconf))) +
  scale_x_datetime(limits = c(earliest_test_case, latest_date_plus1day)) +
  ylab('Number of tests')

#Get gg object - cases/tests

p_case_to_test <- ggplot() +
  geom_point(data = covid_test, aes(x = Date, y = numconf/numtested, group = prname), alpha = 0.2) +
  geom_line(data = covid_test, aes(x = Date, y = numconf/numtested, colour = prname)) +
  geom_label_repel(data = covid_test_latest, aes(x = Date, y = numconf/numtested, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  #scale_y_continuous(trans = 'log2', limits = c(1, max(covid_case$numconf))) +
  scale_x_datetime(limits = c(earliest_test_case, latest_date_plus1day)) +
  ylab('Cumulative number of cases/Cumulative number of tests')


daily_test_latest <- daily_cases_df

#Get gg object = new cases/new tests
p_case_to_test_daily <- ggplot() +
  geom_point(data = daily_cases_df, aes(x = Date, y = new_cases/new_tests, group = prname), alpha = 0.2) +
  geom_line(data = daily_cases_df, aes(x = Date, y = new_cases/new_tests, colour = prname)) +
  geom_label_repel(data = data.frame(daily_case_label), aes(x = label_Date, y = label_case/label_test, label = prname), size = 2, box.padding = 0.7, alpha = 0.5) +
  scale_y_continuous(trans = 'log2', limits = c(1, max(covid_case$numconf))) +
  scale_x_datetime(limits = c(earliest_test_case, latest_date_plus1day)) +
  ylab('Number of cases/Number of tests')

```

<!-- Column {.tabset .tabset-fade} -->
<!-- ------------------------------------- -->

<!-- ### Number of tests - Cumulative -->
<!-- ```{r, 'fig.width' = 10, 'fig.cap' = '**Note that early data on testing is not available from this source'} -->

<!-- print(p_tests) -->

<!-- ``` -->

<!-- ###Number of tests - Daily -->
<!-- ```{r, 'fig.width' = 10, 'fig.cap' = '**Note that early data on testing is not available from this source'} -->

<!-- print(p_test_daily) -->

<!-- ``` -->


<!-- ### Case to test ratio - Cumulative -->
<!-- ```{r, 'fig.width' = 10, 'fig.cap' = '**Note that early data on testing is not available from this source'} -->

<!-- print(p_case_to_test) -->

<!-- ``` -->

<!-- ###Case to test ratio - Daily -->

<!-- ```{r, 'fig.width' = 10, 'fig.cap' = '**Note that early data on testing is not available from this source'} -->

<!-- print(p_case_to_test_daily) -->

<!-- ``` -->

Data warnings
===

The following dates have NAs in raw data for number of confirmed cases
```{r}

print(na_casescnf)

```

The following dates have NAs in raw data for number of deaths

```{r}

print(na_death)

```
